theme: jekyll-theme-hacker
# Site settings
title: Xh4H
baseurl: "" # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until "baseurl:"
  Xh4H | Pwning, web hacking...
